services:

  db:
    image: postgres:18
    container_name: battlegrid_db
    environment:
      POSTGRES_DB: BattleGridDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"   # Maps local port 5433 -> container's 5432
    volumes:
      - pgdata:/var/lib/postgresql
      - ./BattleGrid.Infrastructure/DatabaseCodes:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d BattleGridDB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: BattleGrid.API/Dockerfile
    container_name: battlegrid_api
    ports:
      - "4744:10000"    # Maps local port 4744 -> container's 10000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:10000
      ConnectionStrings__BattleGridDB: "Host=db;Port=5432;Database=BattleGridDB;Username=postgres;Password=1234;Include Error Detail=true"
      Jwt__Secret: "LongAndSecureEnoughSigningKeyForBattleGrid321!"
      Jwt__Issuer: "BattleGrid_Server"
      Jwt__Audience: "BattleGrid_User"
      Cors__AllowedOrigins__0: "http://localhost:4746"

    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: BattleGrid.Web/Dockerfile
    container_name: battlegrid_web
    ports:
      - "4746:10000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:10000
      ApiBaseUrl: "http://api:10000"
    depends_on:
      - api
    restart: on-failure

volumes:
  pgdata: